baseurl: ''
include: ['_pages']
exclude: ['README.md', 'package.json', 'node_modules/', 'gulpfile.js']
includes_dir: ./_includes
data_dir: ./_data
permalink: /:categories/:title/

googleApiKey: 'AIzaSyAxCaMM8L-qQk8H3MhtbkQtAh65-IpTkNI'
